#!/usr/bin/env node
// kb-build.mjs — publish a department EDITION of this base: everything marked `company`
// plus everything marked `department` for that one department. Nothing else is written,
// so nothing else can land on that team's disk.
//
// Usage:  node scripts/kb-build.mjs --dept sales --out ../kb-sales
//         node scripts/kb-build.mjs --dept sales --out ../kb-sales --dry
//
// Direction: DOWN (master → edition). The reverse trip is kb-collect.mjs.
//
// Ownership is per path and there is exactly one writer for each, which is why the two
// directions never fight over a file:
//   • master-owned paths  → overwritten on every build
//   • edition-owned paths (access.writable) → written only when ABSENT, never overwritten;
//     the team is the source of truth there and kb-collect carries their edits back up.
//
// Never force-push the result: the edition repo also holds the team's own commits.

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync, cpSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, sep, dirname, extname } from 'node:path';
import { readConfig, frontmatter, classify, readableByDepartment, isWritable, writablePaths } from './kb-access.mjs';

const ROOT = process.cwd();
const arg = n => { const i = process.argv.indexOf(n); return i > -1 ? process.argv[i + 1] : ''; };
const DEPT = arg('--dept');
const OUT = arg('--out');
const DRY = process.argv.includes('--dry');

// Generated by reindex — every edition rebuilds its own, so shipping them would only
// hand the team a stale index of a base they cannot see.
const GENERATED = new Set(['INDEX.md', 'INDEX-facets.md', 'INSIGHTS.md', 'GAPS.md', 'LESSONS.md',
  'BOARD.md', 'ALIGNMENT.md', 'kb-data.js', 'graph.json', '.quotes.lock.json']);
// Zone indexes are generated too (`<zone>/INDEX.md`, paginated `INDEX.pN.md`). They must
// never ship: an index lists articles by title and summary, including ones this edition
// is not allowed to receive — shipping it would leak exactly what we withheld.
const GENERATED_INDEX = /^INDEX(\.p\d+)?\.md$/;
// Local-only zones: raw source, work memory, eval fixtures. Never leave the master.
const LOCAL_ONLY = new Set(['raw', 'memory', 'eval', '.git', 'node_modules']);
// The engine itself — copied verbatim so the edition is a fully working base.
const ENGINE = ['scripts', 'viewer.html', 'AGENTS.md', '_templates', 'kb'];

if (!DEPT || !OUT) {
  console.error('Usage: kb-build.mjs --dept <slug> --out <dir> [--dry]');
  process.exit(2);
}
const config = readConfig(ROOT);
const access = config.access || {};
const departments = config.departments || [];
if (departments.length && !departments.includes(DEPT)) {
  console.error(`✗ Unknown department "${DEPT}". Configured: ${departments.join(', ')}`);
  process.exit(2);
}

// ── Collect every candidate file (content, not engine) ───────────────────────
function walk(dir, acc = []) {
  let entries;
  try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return acc; }
  for (const e of entries) {
    const rel = relative(ROOT, join(dir, e.name)).split(sep).join('/');
    if (LOCAL_ONLY.has(e.name) || GENERATED.has(rel) || GENERATED_INDEX.test(e.name)) continue;
    if (e.name.startsWith('.')) continue;
    if (ENGINE.includes(rel)) continue;                       // copied wholesale later
    if (e.isDirectory()) walk(join(dir, e.name), acc);
    else if (['.md', '.json'].includes(extname(e.name)) && rel !== 'knowledge.config.json') acc.push(rel);
  }
  return acc;
}

const candidates = walk(ROOT);
const kept = [], dropped = [];
for (const rel of candidates) {
  const isMd = extname(rel) === '.md';
  const meta = isMd ? frontmatter(readFileSync(join(ROOT, rel), 'utf8')) : {};
  const cls = classify(rel, meta, access);
  (readableByDepartment(cls, DEPT) ? kept : dropped).push({ rel, cls, meta });
}

// ── Rewrite [[links]] that point outside the edition ─────────────────────────
// Without this the team's lint fills up with dead references to articles they were
// never meant to see, and they stop reading lint at all.
const keptSlugs = new Set(kept.map(k => k.meta.slug || k.rel.split('/').pop().replace(/\.md$/, '')));
let rewritten = 0;
function rewriteLinks(text) {
  return text.split(/(```[\s\S]*?```)/g).map(seg => {
    if (seg.startsWith('```')) return seg;                     // leave code fences alone
    return seg.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (whole, slug, label) => {
      if (keptSlugs.has(slug.trim())) return whole;
      rewritten++;
      return `${(label || slug).trim()} (outside your edition)`;
    });
  }).join('');
}

// ── Write ────────────────────────────────────────────────────────────────────
let written = 0, preserved = 0;
// Manifest of what THIS build put into master-owned paths, by content hash. kb-collect
// reads it to tell a real edit apart from our own link rewriting — without it every
// rewritten file looks tampered with on the way back and the report becomes noise.
const manifest = {};
const sha = s => createHash('sha256').update(s).digest('hex').slice(0, 16);

function put(rel, content) {
  // Edition-owned paths: seed once, then never touch. The team owns them from there on.
  if (isWritable(rel, DEPT, access) && existsSync(join(OUT, rel))) { preserved++; return; }
  if (!isWritable(rel, DEPT, access)) manifest[rel] = sha(content);
  written++;
  if (DRY) return;
  const p = join(OUT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
}

if (!DRY) mkdirSync(OUT, { recursive: true });

for (const k of kept) {
  const raw = readFileSync(join(ROOT, k.rel), 'utf8');
  put(k.rel, extname(k.rel) === '.md' ? rewriteLinks(raw) : raw);
}

// Master-owned content that vanished from the master must vanish from the edition too —
// otherwise a reclassified article lingers on the team's disk forever.
let removed = 0;
if (existsSync(OUT)) {
  const keptSet = new Set(kept.map(k => k.rel));
  const walkOut = (dir, acc = []) => {
    let entries; try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return acc; }
    for (const e of entries) {
      const full = join(dir, e.name);
      const rel = relative(OUT, full).split(sep).join('/');
      if (e.name.startsWith('.') || LOCAL_ONLY.has(e.name) || ENGINE.includes(rel) || GENERATED_INDEX.test(e.name)) continue;
      if (e.isDirectory()) walkOut(full, acc);
      else if (['.md', '.json'].includes(extname(e.name)) && rel !== 'knowledge.config.json') acc.push(rel);
    }
    return acc;
  };
  for (const rel of walkOut(OUT)) {
    if (keptSet.has(rel) || isWritable(rel, DEPT, access) || GENERATED.has(rel)) continue;
    removed++;
    if (!DRY) rmSync(join(OUT, rel), { force: true });
  }
}

// Engine + edition config
if (!DRY) {
  for (const e of ENGINE) {
    const src = join(ROOT, e);
    if (existsSync(src)) cpSync(src, join(OUT, e), { recursive: true });
  }
  const editionConfig = {
    ...config,
    remote: '',
    departments: [DEPT],
    edition: { department: DEPT, upstream: config.company?.slug || '' },
  };
  writeFileSync(join(OUT, 'knowledge.config.json'), JSON.stringify(editionConfig, null, 2) + '\n');
  writeFileSync(join(OUT, '.gitignore'), gitignoreFor(kept));
  writeFileSync(join(OUT, '.kb-edition.json'), JSON.stringify({ department: DEPT, files: manifest }, null, 2) + '\n');
}

// Whitelist .gitignore, same doctrine as the master: ignore everything, re-allow only
// the zones actually present. A stray file cannot reach the remote by accident.
function gitignoreFor(list) {
  const tops = [...new Set(list.map(k => k.rel.includes('/') ? k.rel.split('/')[0] + '/' : k.rel))].sort();
  const allow = ['.gitignore', '.kb-edition.json', 'AGENTS.md', 'knowledge.config.json', 'viewer.html', 'scripts', 'kb', '_templates',
    ...writablePaths(DEPT, access).map(p => p.replace(/\/$/, '')), ...tops.map(t => t.replace(/\/$/, ''))];
  return ['# Whitelist .gitignore — ignore everything, re-allow only this edition\'s zones.',
    '/*', ...[...new Set(allow)].sort().map(a => `!/${a}`), '',
    '# Generated by reindex — rebuilt locally, never shared.',
    ...[...GENERATED].map(g => `/${g}`), ''].join('\n');
}

console.log(`kb-build${DRY ? ' (dry run)' : ''} — edition "${DEPT}" → ${OUT}`);
console.log(`  kept      : ${kept.length} file(s)`);
console.log(`  withheld  : ${dropped.length} file(s) (owners-only or another department)`);
console.log(`  written   : ${written}`);
if (preserved) console.log(`  preserved : ${preserved} (edition-owned — the team writes these)`);
if (removed) console.log(`  removed   : ${removed} (no longer readable by this department)`);
if (rewritten) console.log(`  links     : ${rewritten} rewritten (target outside the edition)`);
